// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgDbNokrv4DC5XpG7CCTXa6EpECexvcSw',
    appId: '1:728869985472:web:a8752b97aa1101b3216125',
    messagingSenderId: '728869985472',
    projectId: 'cobafire-e80ff',
    authDomain: 'cobafire-e80ff.firebaseapp.com',
    storageBucket: 'cobafire-e80ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJwMRl4UA7BoVcCj_CFVFyKuxvxZz5_W8',
    appId: '1:728869985472:android:bb237fc7e558a8df216125',
    messagingSenderId: '728869985472',
    projectId: 'cobafire-e80ff',
    storageBucket: 'cobafire-e80ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBtqxqNElM8m1AaJhtbRy86ZuNQuvw3gs',
    appId: '1:728869985472:ios:d5f512c67517448b216125',
    messagingSenderId: '728869985472',
    projectId: 'cobafire-e80ff',
    storageBucket: 'cobafire-e80ff.appspot.com',
    iosClientId:
        '728869985472-kqta55qnitmlt74n0nrjbmvab2b0snsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBtqxqNElM8m1AaJhtbRy86ZuNQuvw3gs',
    appId: '1:728869985472:ios:d5f512c67517448b216125',
    messagingSenderId: '728869985472',
    projectId: 'cobafire-e80ff',
    storageBucket: 'cobafire-e80ff.appspot.com',
    iosClientId:
        '728869985472-kqta55qnitmlt74n0nrjbmvab2b0snsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );
}
